using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("igorbrejc.net")]
[assembly: AssemblyProductAttribute("GroundTruth")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2008-2012 Igor Brejc.")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyFileVersionAttribute("1.8.2002")]
[assembly: AssemblyInformationalVersionAttribute("1.8")]
[assembly: ComVisible(false)]
[assembly: AssemblyConfigurationAttribute("Release")]
